location = "East US"
resource_group_name = "rg-banking-portal"
b2c_tenant_name = "myb2ctenant"
keyvault_name = "keyvault-banking"
sql_server_name = "sqlserver-banking"
sql_db_name = "sqldb-banking"
servicebus_namespace_name = "servicebus-banking"
sql_admin_password = "ChangeThisPassword123!"
