resource_group_name = "example-resource-group"
location           = "West Europe"
sql_admin_username = "adminuser"
sql_admin_password = "P@ssw0rd123"
domain_name        = "example.com"
user_principal_name = "user@example.com"
