project_name = "self_service_banking"
resource_group_name = "self_service_banking_rg"
location = "East US"
b2c_name = "self_service_banking_b2c"
key_vault_name = "self_service_banking_kv"
tenant_id = "your-tenant-id"
sql_admin_username = "sqladmin"
sql_admin_password = "your-password"
